// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(StoreGamesContext))]
    [Migration("20230306172521_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameGame")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.Property<string>("Studio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StyleGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StyleGameId");

                    b.ToTable("CompGame");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameGame = "Need for Speed",
                            Release = new DateTime(2015, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = "EAGames Sports",
                            StyleGameId = 1
                        },
                        new
                        {
                            Id = 2,
                            NameGame = "Contro Strike",
                            Release = new DateTime(2015, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = "Valve",
                            StyleGameId = 2
                        },
                        new
                        {
                            Id = 3,
                            NameGame = "My little pony",
                            Release = new DateTime(2015, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = "Valve",
                            StyleGameId = 2
                        },
                        new
                        {
                            Id = 4,
                            NameGame = "S.T.A.L.K.E.R 2",
                            Release = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = "GSC",
                            StyleGameId = 1
                        },
                        new
                        {
                            Id = 5,
                            NameGame = "Heroes 3.5",
                            Release = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = "GSC",
                            StyleGameId = 4
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.StyleGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StyleGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Info ArcadRaising...",
                            Name = "ArcadRaising"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Info Shooter...",
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Info Raising...",
                            Name = "Raising"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Comand game.....",
                            Name = "Strategy"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Game", b =>
                {
                    b.HasOne("DataAccess.Entities.StyleGame", "StyleGame")
                        .WithMany("Games")
                        .HasForeignKey("StyleGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StyleGame");
                });

            modelBuilder.Entity("DataAccess.Entities.StyleGame", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
